"""added on delete effect to models

Revision ID: 029dd6acf00f
Revises: dc831d492bb7
Create Date: 2025-04-29 20:27:24.259676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '029dd6acf00f'
down_revision: Union[str, None] = 'dc831d492bb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('appointments_doctor_id_fkey', 'appointments', type_='foreignkey')
    op.drop_constraint('appointments_available_time_slot_id_fkey', 'appointments', type_='foreignkey')
    op.drop_constraint('appointments_patient_id_fkey', 'appointments', type_='foreignkey')
    op.create_foreign_key(None, 'appointments', 'users', ['patient_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'appointments', 'available_time_slots', ['available_time_slot_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'appointments', 'users', ['doctor_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('available_time_slots_doctor_id_fkey', 'available_time_slots', type_='foreignkey')
    op.create_foreign_key(None, 'available_time_slots', 'users', ['doctor_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('doctor_profiles_user_id_fkey', 'doctor_profiles', type_='foreignkey')
    op.create_foreign_key(None, 'doctor_profiles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'doctor_profiles', type_='foreignkey')
    op.create_foreign_key('doctor_profiles_user_id_fkey', 'doctor_profiles', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'available_time_slots', type_='foreignkey')
    op.create_foreign_key('available_time_slots_doctor_id_fkey', 'available_time_slots', 'users', ['doctor_id'], ['id'])
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.create_foreign_key('appointments_patient_id_fkey', 'appointments', 'users', ['patient_id'], ['id'])
    op.create_foreign_key('appointments_available_time_slot_id_fkey', 'appointments', 'available_time_slots', ['available_time_slot_id'], ['id'])
    op.create_foreign_key('appointments_doctor_id_fkey', 'appointments', 'users', ['doctor_id'], ['id'])
    # ### end Alembic commands ###
