"""added forward and backward relationship to doctorprofile and user

Revision ID: 9a5efc1d8f93
Revises: 66597edeb17d
Create Date: 2025-04-29 16:01:29.610191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a5efc1d8f93'
down_revision: Union[str, None] = '66597edeb17d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
